### ISSUE TITLE
General requirements (checklist para verificarmos antes de entregar)

### ISSUE THREAD

**Issue by sgkhusal** [eliarisalvares/webserv_42sp#1]
PDF requirements:

- [ ] Your program should not crash in any circumstances (even when it runs out of memory), and should not quit unexpectedly. If it happens, your project will be considered non-functional and your grade will be 0
- [x] You can’t execve another web server
- [ ] Your server must never block and the client can be bounced properly if necessary
- [ ] It must be non-blocking and use only 1 poll() (or equivalent) for all the I/O operations between the client and the server (listen included).
- [ ] poll() (or equivalent) must check read and write at the same time.
- [x] You must never do a read or a write operation without going through poll() (or equivalent).  if you try to read/recv or write/send in any file descriptor without using poll() (or equivalent), your grade will be 0.
- [x] Checking the value of errno is strictly forbidden after a read or a write operation
- [x] You don’t need to use poll() (or equivalent) before reading your configuration file
- [x] A request to your server should never hang forever (acho que é a questão de blocking)
- [x] NGINX compatível com HTTP 1.1
- [x] You must be able to serve a fully static website
- [ ] The important thing is resilience. Your server should never die.

**Comment by sgkhusal** [comment]
-

**Comment by ferfahl** [comment]
Some other requirements

- [ ] Explanation of the basics HTTP server
- [ ] Explanation of the basics of CGI
- [ ] Explanation of the function used for I/O Multiplexing
- [ ] Explanation of the _select()_ function
- [ ] If used only one _select()_ and how it was managed for the server to accept and the client to read/write
- [ ] _select()_ must be in the main loop and should check file descriptors for read and write AT THE SAME TIME
- [ ] There should be only one read or one write per client per _select()_. Explain the use of the _select()_ for this purpose (from the _select()_ to the read and write of a client)
- [ ] All _read, recv, write, send_ on a socket must check if an error is returned and remove the client
- [ ] All _read, recv, write, send_ must have a check for the value returned (checking BOTH -1 or 0)
- [ ] **MUST NOT USE errno**
- [ ] All writing and reading MUST go through the select, any other is forbidden
- [ ] GET, POST and DELETE request should work
- [ ] UNKNOWN requests should not result in a crash
- [ ] Every test made should receive the appropriate status code
- [ ] The server must accept an uploaded file and the user must be able to download it
- [ ] Use the reference browser of the team, opening the network part of it and trying to connect to the server using it
- [ ] Look at the server header and the response header

Makefile
- [x] Must not relink during compilation

Config
- [x] Every return of the HTTP must be according to the status code list
- [x] Setup multiple servers with different ports
- [x] Setup multiple servers with different hostnames
- [x] Setup different websites
- [x] Setup the default error page (must be able to change from the 404 error)
- [ ] Limit the client body 
- [x] Setup routes in a server to different directories
- [x] Setup a default file to search if you ask for a directory
- [x] Setup a list of methods accepted for a certain route (try to delete with and without permission)
- [x] Launch multiple servers at the same time with different configurations but same ports -> if so, explain why the server should work if one of the configuration files isn't functional

CGI
- [ ] The server is working fine with the CGI
- [ ] The CGI should run in the correct directory for relative path file access
- [x] Must work with the GET and POST methods
- [ ] Need to be tested with files containing errors to check how the error handling are being treated.
- [ ] Can be tested with a script for an infinite loop or an error -> free to do any tests

Erros/Handling
- [x] Using a incorrect URL on the server
- [x] List a directory
- [x] Redirect a URL
- [x] In the config file, try to setup the same port multiple times (must now work)
- [x] Use _siege_(command) to run some stress tests
- [x] Availability should be above 99,5% for a simple GET on an empty page (using _siege -b_ on that page)
- [ ] Must not have any memory leak (checked with monitoring the process memory usage, it must not go up indefinitely)
- [ ] Must not be any _hanging_ connection
- [x] Should be able to use _siege_ indefinitely
